# Generated by Django 2.2.2 on 2019-06-24 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('Data_Inicio', models.DateField(verbose_name='Abertura do ano letivo')),
                ('Data_Fim', models.DateField(verbose_name='Fechamento do ano letivo')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bimestre', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Bimestre')),
                ('Data_Inicio', models.DateField(verbose_name='Abertura do bimestre')),
                ('Data_Limite_Notas', models.DateField(verbose_name='Limite do lançamento das Notas')),
                ('Data_Fim', models.DateField(verbose_name='Fechamento do bimestre')),
                ('AnoLetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.AnoLetivo', verbose_name='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rua', models.CharField(max_length=40, verbose_name='Rua')),
                ('Numero', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('Bairro', models.CharField(max_length=40, verbose_name='Bairro')),
                ('Cidade', models.CharField(max_length=40, verbose_name='Cidade')),
                ('Estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('Complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('Zona', models.CharField(choices=[('URB', 'Urbana'), ('RUR', 'Rural')], default='URB', max_length=15, verbose_name='Zona')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('Email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('Nivel_Escolaridade', models.CharField(choices=[('F', 'Ensino Fundamental'), ('M', 'Ensino Médio'), ('FM', 'Ensino Fundamental e Médio')], default='F', max_length=20, verbose_name='Nível Escolaridade')),
                ('Tipo_Escola', models.CharField(choices=[('Pub', 'Pública'), ('Pri', 'Privada')], default='Pub', max_length=20, verbose_name='Tipo da Escola')),
                ('Nota_de_Corte', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Nota de corte de aprovação')),
                ('Endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Endereco', verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Leciona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aulas_Previstas', models.PositiveSmallIntegerField(verbose_name='Aulas Previstas')),
                ('Disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Disciplina', verbose_name='Disciplina')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo')),
                ('Data_Nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('Cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('Rg', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='RG')),
                ('Escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestaoEscolar.Pessoa')),
                ('Ra', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RA')),
                ('Cidade_Nascimento', models.CharField(max_length=40, verbose_name='Cidade de Nascimento')),
                ('Estado_Nascimento', models.CharField(max_length=40, verbose_name='Estado de Nascimento')),
                ('Nacionalidade', models.CharField(max_length=20, verbose_name='Nacionalidade')),
                ('Irmao_Gemeo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=10, verbose_name='Irmão Gêmeo')),
                ('Nome_Pai', models.CharField(max_length=40, verbose_name='Nome do Pai')),
                ('Nome_Mae', models.CharField(max_length=40, verbose_name='Nome da Mãe')),
                ('Necessidade_Educacional_Especial', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=10, verbose_name='Necessidade Educacional Especial')),
                ('Superdotacao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=10, verbose_name='Superdotação/Altas Habilidades')),
                ('Deficiencia', models.CharField(choices=[('nao_possui', 'Não Possui'), ('multipla', 'Múltipla'), ('cegueira', 'Cegueira'), ('baixa_visao', 'Baixa Visão'), ('surdez_severa_ou_profunda', 'Surdez Severa ou Profunda'), ('surdez_severa_ou_moderada', 'Surdez Leve ou Moderada'), ('surdocegueira', 'Surdocegueira'), ('fisica_paralisia_cerebral', 'Física – Paralisia Cerebral'), ('fisica_cadeirante', 'Física – Cadeirante'), ('fisica_outros', 'Física – Outros'), ('sindrome_de_down', 'Síndrome de Down'), ('intelectual', 'Intelectual')], default='nao_possui', max_length=40, verbose_name='Deficiência')),
                ('Transtorno_Global_do_Desenvolvimento', models.CharField(choices=[('nao_possui', 'Não Possui'), ('autista_infantil', 'Autista Infantil'), ('sindrome_de_asperger', 'Síndrome de Asperger'), ('sindrome_de_rett', 'Síndrome de Rett'), ('transtorno_desintegrativo_de_infancia', 'Transtorno Desintegrativo de Infância')], default='nao_possui', max_length=40, verbose_name='Transtorno Global do Desenvolvimento')),
                ('Bolsa_Familia', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('gestaoEscolar.pessoa',),
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestaoEscolar.Pessoa')),
                ('Tipo_Gestor', models.CharField(choices=[('G', 'Gestor'), ('D', 'Diretor')], default='G', max_length=20, verbose_name='Tipo de Gestor')),
            ],
            options={
                'abstract': False,
            },
            bases=('gestaoEscolar.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestaoEscolar.Pessoa')),
                ('Titulo', models.CharField(choices=[('E', 'Especialista'), ('M', 'Mestre'), ('D', 'Doutor')], default='E', max_length=20, verbose_name='Título')),
            ],
            options={
                'abstract': False,
            },
            bases=('gestaoEscolar.pessoa',),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestaoEscolar.Pessoa')),
            ],
            options={
                'abstract': False,
            },
            bases=('gestaoEscolar.pessoa',),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('Periodo', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde')], default='M', max_length=20, verbose_name='Período')),
                ('Nivel_Escolaridade', models.CharField(max_length=20, verbose_name='Nível Escolaridade')),
                ('Sala', models.PositiveSmallIntegerField(verbose_name='Sala')),
                ('Max_Alunos', models.PositiveSmallIntegerField(verbose_name='Máximo de Alunos')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=20, verbose_name='Número')),
                ('Escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Pessoa', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(choices=[('B', 'Bimestral'), ('F', 'Final')], default='B', max_length=20, verbose_name='Tipo')),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('AnoLetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.AnoLetivo', verbose_name='Ano')),
                ('Bimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Bimestre', verbose_name='Bimestre')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Leciona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Leciona', verbose_name='Leciona')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('Rm', models.AutoField(primary_key=True, serialize=False, verbose_name='RM')),
                ('Data', models.DateField(auto_now=True, verbose_name='Data da realização da matrícula')),
                ('Situacao', models.CharField(choices=[('matriculado', 'Matriculado'), ('concluido', 'Concluído'), ('transferido', 'Transferido'), ('trancado', 'Trancado')], default='matriculado', max_length=20, verbose_name='Situação')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
            ],
        ),
        migrations.AddField(
            model_name='leciona',
            name='Turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Turma', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Presenca', models.BooleanField(default=True, verbose_name='Presença')),
                ('Aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Aula', verbose_name='Aula')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='Pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='Escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='bimestre',
            name='Escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tema', models.CharField(max_length=30, verbose_name='Tema')),
                ('Peso', models.PositiveSmallIntegerField(verbose_name='Peso')),
                ('Aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Aula', verbose_name='Aula')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='Escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='aula',
            name='Leciona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Leciona', verbose_name='Leciona'),
        ),
        migrations.AddField(
            model_name='aula',
            name='Turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Turma', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('Avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Avaliacao', verbose_name='Avaliação')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
            ],
        ),
        migrations.AddField(
            model_name='anoletivo',
            name='Escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('Nome', 'Escola'), name='unique_Turma'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('Sala', 'Periodo', 'Escola'), name='unique_Sala_Turma_Periodo'),
        ),
        migrations.AddField(
            model_name='nota',
            name='Aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='Aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='leciona',
            name='Professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Professor', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='Aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='escola',
            name='Diretor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Gestor', verbose_name='Diretor'),
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.UniqueConstraint(fields=('Nome', 'Escola'), name='unique_Disciplina'),
        ),
        migrations.AddConstraint(
            model_name='bimestre',
            constraint=models.UniqueConstraint(fields=('AnoLetivo', 'Bimestre', 'Escola'), name='unique_Ano_Bimestre'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='Aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Aluno', verbose_name='Aluno'),
        ),
        migrations.AddConstraint(
            model_name='anoletivo',
            constraint=models.UniqueConstraint(fields=('Ano', 'Escola'), name='unique_Ano'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='Turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Turma', verbose_name='Turma'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('AnoLetivo', 'Bimestre', 'Aluno', 'Leciona', 'Escola'), name='unique_Ano_Bimestre_Aluno_Leciona'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('AnoLetivo', 'Aluno', 'Leciona', 'Escola'), name='unique_Ano_Aluno_Leciona'),
        ),
        migrations.AddConstraint(
            model_name='leciona',
            constraint=models.UniqueConstraint(fields=('Disciplina', 'Turma', 'Escola'), name='unique_Leciona'),
        ),
        migrations.AddConstraint(
            model_name='frequencia',
            constraint=models.UniqueConstraint(fields=('Aula', 'Aluno'), name='unique_Aula_Aluno'),
        ),
        migrations.AddConstraint(
            model_name='aplicacao',
            constraint=models.UniqueConstraint(fields=('Avaliacao', 'Aluno'), name='unique_Avaliacao_Aluno'),
        ),
    ]
