# Generated by Django 2.2.2 on 2019-06-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(error_messages={'blank': 'Este campo não pode ser vazio'}, max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Nivel_Escolaridade', models.CharField(choices=[('F', 'Ensino Fundamental'), ('M', 'Ensino Médio'), ('FM', 'Ensino Fundamental e Médio')], default='F', max_length=20)),
                ('Tipo_Escola', models.CharField(choices=[('Pub', 'Pública'), ('Pri', 'Privada')], default='Pub', max_length=20)),
            ],
        ),
    ]
