# Generated by Django 2.2.2 on 2019-06-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rua', models.CharField(max_length=40)),
                ('Numero', models.PositiveSmallIntegerField()),
                ('Bairro', models.CharField(max_length=40)),
                ('Cidade', models.CharField(max_length=40)),
                ('Estado', models.CharField(max_length=2)),
                ('Complemento', models.CharField(max_length=100)),
                ('Zona', models.CharField(choices=[('URB', 'Urbana'), ('RUR', 'Rural')], default='URB', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Nivel_Escolaridade', models.CharField(choices=[('F', 'Ensino Fundamental'), ('M', 'Ensino Médio'), ('FM', 'Ensino Fundamental e Médio')], default='F', max_length=20)),
                ('Tipo_Escola', models.CharField(choices=[('Pub', 'Pública'), ('Pri', 'Privada')], default='Pub', max_length=20)),
                ('Endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('Data_Nascimento', models.DateField()),
                ('Cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('Rg', models.CharField(blank=True, max_length=9, null=True)),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestaoEscolar.Pessoa')),
                ('Ra', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Cidade_Nascimento', models.CharField(max_length=40)),
                ('Estado_Nascimento', models.CharField(max_length=40)),
                ('Nacionalidade', models.CharField(max_length=20)),
                ('Irmao_Gemeo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=10)),
                ('Nome_Pai', models.CharField(max_length=40)),
                ('Nome_Mae', models.CharField(max_length=40)),
                ('Necessidade_Educacional_Especial', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=10)),
                ('Superdotacao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=10)),
                ('Deficiencia', models.CharField(choices=[('multipla', 'Múltipla'), ('cegueira', 'Cegueira'), ('baixa_visao', 'Baixa Visão'), ('surdez_severa_ou_profunda', 'Surdez Severa ou Profunda'), ('surdez_severa_ou_moderada', 'Surdez Leve ou Moderada'), ('surdocegueira', 'Surdocegueira'), ('fisica_paralisia_cerebral', 'Física – Paralisia Cerebral'), ('fisica_cadeirante', 'Física – Cadeirante'), ('fisica_outros', 'Física – Outros'), ('sindrome_de_down', 'Síndrome de Down'), ('intelectual', 'Intelectual'), ('nao_possui', 'Não Possui')], default='multipla', max_length=40)),
                ('Transtorno_Global_do_Desenvolvimento', models.CharField(choices=[('autista_infantil', 'Autista Infantil'), ('sindrome_de_asperger', 'Síndrome de Asperger'), ('sindrome_de_rett', 'Síndrome de Rett'), ('transtorno_desintegrativo_de_infancia', 'Transtorno Desintegrativo de Infância')], default='autista_infantil', max_length=40)),
                ('Bolsa_Familia', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('gestaoEscolar.pessoa',),
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestaoEscolar.Pessoa')),
            ],
            options={
                'abstract': False,
            },
            bases=('gestaoEscolar.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestaoEscolar.Pessoa')),
                ('Titulo', models.CharField(choices=[('E', 'Especialista'), ('M', 'Mestre'), ('D', 'Doutor')], default='E', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('gestaoEscolar.pessoa',),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestaoEscolar.Pessoa')),
            ],
            options={
                'abstract': False,
            },
            bases=('gestaoEscolar.pessoa',),
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=20)),
                ('Escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola')),
                ('Pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='Pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Pessoa'),
        ),
        migrations.AddField(
            model_name='escola',
            name='Diretor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Gestor'),
        ),
    ]
