# Generated by Django 2.2.2 on 2019-06-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='Data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='Rm',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='RM'),
        ),
    ]
