# Generated by Django 2.2.2 on 2019-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Deficiencia',
            field=models.CharField(choices=[('nao_possui', 'Não Possui'), ('multipla', 'Múltipla'), ('cegueira', 'Cegueira'), ('baixa_visao', 'Baixa Visão'), ('surdez_severa_ou_profunda', 'Surdez Severa ou Profunda'), ('surdez_severa_ou_moderada', 'Surdez Leve ou Moderada'), ('surdocegueira', 'Surdocegueira'), ('fisica_paralisia_cerebral', 'Física – Paralisia Cerebral'), ('fisica_cadeirante', 'Física – Cadeirante'), ('fisica_outros', 'Física – Outros'), ('sindrome_de_down', 'Síndrome de Down'), ('intelectual', 'Intelectual')], default='nao_possui', max_length=40),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='Transtorno_Global_do_Desenvolvimento',
            field=models.CharField(choices=[('nao_possui', 'Não Possui'), ('autista_infantil', 'Autista Infantil'), ('sindrome_de_asperger', 'Síndrome de Asperger'), ('sindrome_de_rett', 'Síndrome de Rett'), ('transtorno_desintegrativo_de_infancia', 'Transtorno Desintegrativo de Infância')], default='nao_possui', max_length=40),
        ),
    ]
