# Generated by Django 2.2.2 on 2019-06-17 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='Nome',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=20)),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rua', models.CharField(max_length=40)),
                ('Numero', models.PositiveSmallIntegerField()),
                ('Bairro', models.CharField(max_length=40)),
                ('Cidade', models.CharField(max_length=40)),
                ('Estado', models.CharField(max_length=2)),
                ('Complemento', models.CharField(max_length=100)),
                ('Zona', models.CharField(choices=[('URB', 'Urbana'), ('RUR', 'Rural')], default='URB', max_length=15)),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola')),
            ],
        ),
    ]
