# Generated by Django 2.2.2 on 2019-06-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turma',
            name='unique_Sala_Turma_Periodo',
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('Sala', 'Periodo', 'Escola'), name='unique_Sala_Turma_Periodo'),
        ),
    ]
