# Generated by Django 2.2.2 on 2019-06-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='Periodo',
            field=models.CharField(max_length=20, verbose_name='Período'),
        ),
    ]
