# Generated by Django 2.2.2 on 2019-06-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0002_auto_20190619_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='Periodo',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde')], default='M', max_length=20, verbose_name='Período'),
        ),
    ]
