# Generated by Django 2.2.2 on 2019-06-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0002_auto_20190617_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Nome', models.CharField(max_length=50)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('Data_Nascimento', models.DateField()),
                ('Cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('Rg', models.CharField(blank=True, max_length=9, null=True)),
                ('Nome_Usuario', models.CharField(max_length=40, unique=True)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
