# Generated by Django 2.2.2 on 2019-06-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0002_auto_20190626_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='Endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Endereco', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='Complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
    ]
