# Generated by Django 2.2.2 on 2019-06-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0002_auto_20190621_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('Data_Inicio', models.DateField(verbose_name='Abertura do ano letivo')),
                ('Data_Fim', models.DateField(verbose_name='Fechamento do ano letivo')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
            ],
        ),
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bimestre', models.PositiveSmallIntegerField(verbose_name='Bimestre')),
                ('Data_Inicio', models.DateField(verbose_name='Abertura do bimestre')),
                ('Data_Limite_Notas', models.DateField(verbose_name='Limite do lançamento das Notas')),
                ('Data_Fim', models.DateField(verbose_name='Fechamento do bimestre')),
                ('AnoLetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.AnoLetivo', verbose_name='Ano')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(choices=[('B', 'Bimestral'), ('F', 'Final')], default='B', max_length=20, verbose_name='Tipo')),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('Aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Aluno', verbose_name='Aluno')),
                ('AnoLetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.AnoLetivo', verbose_name='Ano')),
                ('Bimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Bimestre', verbose_name='Bimestre')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Leciona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Leciona', verbose_name='Leciona')),
            ],
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('AnoLetivo', 'Bimestre', 'Aluno', 'Leciona', 'Escola'), name='unique_Ano_Bimestre_Aluno_Leciona'),
        ),
        migrations.AddConstraint(
            model_name='bimestre',
            constraint=models.UniqueConstraint(fields=('AnoLetivo', 'Bimestre', 'Escola'), name='unique_Ano_Bimestre'),
        ),
        migrations.AddConstraint(
            model_name='anoletivo',
            constraint=models.UniqueConstraint(fields=('Ano', 'Escola'), name='unique_Ano'),
        ),
    ]
