# Generated by Django 2.2.2 on 2019-06-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0003_auto_20190621_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='Nota_de_Corte',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Nota de corte de aprovação'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('AnoLetivo', 'Aluno', 'Leciona', 'Escola'), name='unique_Ano_Aluno_Leciona'),
        ),
    ]
