# Generated by Django 2.2.2 on 2019-06-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0003_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='Nome_Usuario',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
    ]
