# Generated by Django 2.2.2 on 2019-06-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0004_auto_20190618_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='Diretor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Gestor'),
        ),
    ]
