# Generated by Django 2.2.2 on 2019-07-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0004_remove_endereco_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='Numero',
            field=models.PositiveIntegerField(error_messages={'required': 'My custom error'}, verbose_name='Número'),
        ),
    ]
