# Generated by Django 2.2.2 on 2019-06-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0004_auto_20190617_2326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
