# Generated by Django 2.2.2 on 2019-06-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0004_auto_20190621_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimestre',
            name='Bimestre',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Bimestre'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='Nota_de_Corte',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Nota de corte de aprovação'),
        ),
    ]
