# Generated by Django 2.2.2 on 2019-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0005_auto_20190622_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='Nota_de_Corte',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Nota de corte de aprovação'),
        ),
    ]
