# Generated by Django 2.2.2 on 2019-06-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0006_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('Data_Nascimento', models.DateField()),
                ('Cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('Rg', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('Data_Nascimento', models.DateField()),
                ('Cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('Rg', models.CharField(blank=True, max_length=9, null=True)),
                ('Titulo', models.CharField(choices=[('E', 'Especialista'), ('M', 'Mestre'), ('D', 'Doutor')], default='E', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('Data_Nascimento', models.DateField()),
                ('Cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('Rg', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
