# Generated by Django 2.2.2 on 2019-06-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0006_auto_20190622_1428'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='escola',
            name='unique_endereco_escola',
        ),
        migrations.AddConstraint(
            model_name='escola',
            constraint=models.UniqueConstraint(fields=('Endereco',), name='unique_endereco_escola'),
        ),
    ]
