# Generated by Django 2.2.2 on 2019-06-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0007_auto_20190622_1452'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='escola',
            name='unique_email_escola',
        ),
        migrations.RemoveConstraint(
            model_name='escola',
            name='unique_endereco_escola',
        ),
        migrations.AlterField(
            model_name='escola',
            name='Email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
