# Generated by Django 2.2.2 on 2019-07-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0015_auto_20190701_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='Escola',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='Pessoa',
        ),
        migrations.AddField(
            model_name='escola',
            name='Telefone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Telefone', verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Telefone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Telefone', verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='Numero1',
            field=models.CharField(default=1111, max_length=20, verbose_name='Número 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='Numero2',
            field=models.CharField(default=2222, max_length=20, verbose_name='Número 2'),
            preserve_default=False,
        ),
    ]
