# Generated by Django 2.2.2 on 2019-07-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0016_auto_20190702_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='Telefone',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='Telefone',
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
