# Generated by Django 2.2.2 on 2019-07-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0017_auto_20190702_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero1', models.CharField(max_length=20, verbose_name='Número 1')),
                ('Numero2', models.CharField(max_length=20, verbose_name='Número 2')),
            ],
        ),
        migrations.AddField(
            model_name='escola',
            name='Telefone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Telefone', verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Telefone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Telefone', verbose_name='Telefone'),
        ),
    ]
