# Generated by Django 2.2.2 on 2019-07-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0020_pessoa_tipo_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Turma', verbose_name='Turma'),
        ),
    ]
