# Generated by Django 2.2.2 on 2019-07-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0021_auto_20190713_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoletivo',
            name='Situacao',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=20, verbose_name='Situação'),
        ),
    ]
