# Generated by Django 2.2.2 on 2019-07-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0022_anoletivo_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimestre',
            name='Situacao',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=20, verbose_name='Situação'),
        ),
    ]
