# Generated by Django 2.2.2 on 2019-07-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0024_auto_20190720_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='AnoLetivo',
        ),
    ]
