# Generated by Django 2.2.2 on 2019-07-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0025_remove_turma_anoletivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='Turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='AnoLetivo',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.AnoLetivo', verbose_name='Ano'),
            preserve_default=False,
        ),
    ]
