# Generated by Django 2.2.2 on 2019-07-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0027_matricula_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='AnoLetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.AnoLetivo', verbose_name='Ano'),
        ),
    ]
