# Generated by Django 2.2.2 on 2019-07-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0029_auto_20190726_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='Nivel_Escolaridade',
        ),
        migrations.AddField(
            model_name='turma',
            name='Serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Serie', verbose_name='Serie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula_turma',
            name='Situacao',
            field=models.CharField(choices=[('matriculado', 'Matriculado'), ('concluido', 'Concluído'), ('transferido', 'Transferido'), ('trancado', 'Trancado'), ('reprovado', 'Reprovado')], default='matriculado', max_length=20, verbose_name='Situação'),
        ),
    ]
