# Generated by Django 2.2.2 on 2019-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0030_auto_20190728_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='Nome',
            field=models.CharField(max_length=2, verbose_name='Nome'),
        ),
    ]
