# Generated by Django 2.2.2 on 2019-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0034_auto_20190728_1541'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turma',
            name='unique_Turma_Ano',
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('Nome', 'Serie', 'AnoLetivo', 'Escola'), name='unique_Turma_Serie_Ano'),
        ),
    ]
