# Generated by Django 2.2.2 on 2019-08-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0035_auto_20190728_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='Escola',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='Leciona',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='Turma',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='Aula',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='Escola',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='Aluno',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='Aula',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='Escola',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='Aluno',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='AnoLetivo',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='Bimestre',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='Escola',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='Leciona',
        ),
        migrations.DeleteModel(
            name='Aplicacao',
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
