# Generated by Django 2.2.2 on 2019-08-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0036_auto_20190801_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leciona',
        ),
    ]
