# Generated by Django 2.2.2 on 2019-08-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0037_delete_leciona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leciona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aulas_Previstas', models.PositiveSmallIntegerField(verbose_name='Aulas Previstas')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Matriz_Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Matriz_Item', verbose_name='Matriz_Item')),
                ('Professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Professor', verbose_name='Professor')),
                ('Turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Turma', verbose_name='Turma')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leciona',
            constraint=models.UniqueConstraint(fields=('Matriz_Item', 'Turma', 'Escola'), name='unique_Leciona_Matriz_Item'),
        ),
    ]
