# Generated by Django 2.2.2 on 2019-08-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0038_auto_20190801_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leciona',
            name='Aulas_Previstas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Aulas Previstas'),
        ),
    ]
