# Generated by Django 2.2.2 on 2019-08-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0041_auto_20190810_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='Tema',
            field=models.CharField(default='nada', max_length=40, verbose_name='Tema'),
            preserve_default=False,
        ),
    ]
