# Generated by Django 2.2.2 on 2019-08-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0043_auto_20190811_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='Presenca',
            field=models.BooleanField(default=False, verbose_name='Presença'),
        ),
    ]
