# Generated by Django 2.2.2 on 2019-08-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0044_auto_20190811_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='Presenca',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], default='Presente', max_length=10, verbose_name='Tema'),
        ),
    ]
