# Generated by Django 2.2.2 on 2019-08-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0045_auto_20190811_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media_Final', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Media_Final')),
                ('AnoLetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.AnoLetivo', verbose_name='AnoLetivo')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Leciona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Leciona', verbose_name='Leciona')),
                ('Matricula_Turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Matricula_Turma', verbose_name='Matricula_Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Nota_Bimestral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Media')),
                ('Bimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Bimestre', verbose_name='Bimestre')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Nota_Final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Nota_Final', verbose_name='Nota_Final')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Valor')),
                ('Peso', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Peso')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Nota_Bimestral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Nota_Bimestral', verbose_name='Nota_Bimestral')),
            ],
        ),
        migrations.AddConstraint(
            model_name='nota_final',
            constraint=models.UniqueConstraint(fields=('AnoLetivo', 'Matricula_Turma', 'Leciona', 'Escola'), name='unique_Nota_Final'),
        ),
    ]
