# Generated by Django 2.2.2 on 2019-08-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0046_auto_20190817_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('Valor', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Valor')),
                ('Peso', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Peso')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Nota_Bimestral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Nota_Bimestral', verbose_name='Nota_Bimestral')),
            ],
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
