# Generated by Django 2.2.2 on 2019-08-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0047_auto_20190817_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_bimestral',
            name='Media',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='nota_final',
            name='Media_Final',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Media_Final'),
        ),
    ]
