# Generated by Django 2.2.2 on 2019-08-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0048_auto_20190817_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimestre',
            name='Data_Fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fechamento do bimestre'),
        ),
        migrations.AlterField(
            model_name='bimestre',
            name='Data_Inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Abertura do bimestre'),
        ),
        migrations.AlterField(
            model_name='bimestre',
            name='Data_Limite_Notas',
            field=models.DateField(blank=True, null=True, verbose_name='Limite do lançamento das Notas'),
        ),
    ]
