# Generated by Django 2.2.2 on 2019-08-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0049_auto_20190817_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='Nota_Bimestral',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='Peso',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='Valor',
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Valor')),
                ('Peso', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Peso')),
                ('Avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Avaliacao', verbose_name='Avaliacao')),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Escola', verbose_name='Escola')),
                ('Nota_Bimestral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Nota_Bimestral', verbose_name='Nota_Bimestral')),
            ],
        ),
    ]
