# Generated by Django 2.2.2 on 2019-08-18 18:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0050_auto_20190818_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='Peso',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0000'), max_digits=2, verbose_name='Peso'),
        ),
    ]
