# Generated by Django 2.2.2 on 2019-08-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0051_auto_20190818_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='Data',
            field=models.DateField(default='2000-02-02', verbose_name='Data'),
            preserve_default=False,
        ),
    ]
