# Generated by Django 2.2.2 on 2019-08-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0052_avaliacao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='Leciona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Leciona', verbose_name='Leciona'),
            preserve_default=False,
        ),
    ]
