# Generated by Django 2.2.2 on 2019-08-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0053_avaliacao_leciona'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='Turma',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Turma', verbose_name='Turma'),
            preserve_default=False,
        ),
    ]
