# Generated by Django 2.2.2 on 2019-08-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0054_avaliacao_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='Avaliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Avaliacao', verbose_name='Avaliacao'),
        ),
    ]
