# Generated by Django 2.2.2 on 2019-08-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0055_auto_20190821_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_bimestral',
            name='Media',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='nota_final',
            name='Media_Final',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Media_Final'),
        ),
    ]
