# Generated by Django 2.2.2 on 2019-08-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0056_auto_20190824_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula_turma',
            name='Situacao',
            field=models.CharField(choices=[('cursando', 'Cursando'), ('aprovado', 'Aprovado'), ('transferido', 'Transferido'), ('trancado', 'Trancado'), ('reprovado', 'Reprovado')], default='cursando', max_length=20, verbose_name='Situação'),
        ),
    ]
