# Generated by Django 2.2.2 on 2019-08-26 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0057_auto_20190825_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='Bimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Bimestre', verbose_name='Bimestre'),
            preserve_default=False,
        ),
    ]
