# Generated by Django 2.2.2 on 2019-10-06 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoEscolar', '0060_auto_20191006_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoletivo',
            options={'verbose_name': 'Ano letivo'},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação'},
        ),
        migrations.AlterModelOptions(
            name='frequencia',
            options={'verbose_name': 'Frequência'},
        ),
        migrations.AlterModelOptions(
            name='leciona',
            options={'verbose_name': 'Disciplina x Professor'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='matricula_turma',
            options={'verbose_name': 'Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='nota_bimestral',
            options={'verbose_name': 'Nota bimestral'},
        ),
        migrations.AlterModelOptions(
            name='nota_final',
            options={'verbose_name': 'Média final'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Série'},
        ),
        migrations.AlterField(
            model_name='aula',
            name='Leciona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Leciona', verbose_name='Disciplina x Professor'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Leciona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Leciona', verbose_name='Disciplina x Professor'),
        ),
        migrations.AlterField(
            model_name='leciona',
            name='Matriz_Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Matriz_Item', verbose_name='Item da matriz'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='Avaliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Avaliacao', verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='Nota_Bimestral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Nota_Bimestral', verbose_name='Média bimestral'),
        ),
        migrations.AlterField(
            model_name='nota_bimestral',
            name='Media',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Média bimestral'),
        ),
        migrations.AlterField(
            model_name='nota_bimestral',
            name='Nota_Final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Nota_Final', verbose_name='Média final'),
        ),
        migrations.AlterField(
            model_name='nota_final',
            name='AnoLetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.AnoLetivo', verbose_name='Ano letivo'),
        ),
        migrations.AlterField(
            model_name='nota_final',
            name='Leciona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Leciona', verbose_name='Disciplina x Professor'),
        ),
        migrations.AlterField(
            model_name='nota_final',
            name='Matricula_Turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Matricula_Turma', verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='nota_final',
            name='Media_Final',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Média final'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='Serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoEscolar.Serie', verbose_name='Série'),
        ),
    ]
